feat(unix): support upgrading Determinate Nix
Add support for upgrading [Determinate Nix][1] on macOS.

[Upgrading Determinate Nix][2] works a little bit different than upgrading
vanilla Nix and running `nix upgrade-nix` will print the following error
message and exit with a non-zero exit code:

> ```
> error: The upgrade-nix command isn't available in Determinate Nix; use sudo determinate-nixd upgrade instead
> ```

This change set checks if `nix` is in fact Determinate Nix and in this
case will run `sudo determinate-nixd upgrade` instead of `nix upgrade-nix`.

[1]: https://determinate.systems/nix/
[2]: https://docs.determinate.systems/determinate-nix/#determinate-nixd-upgrade